### ISSUE TITLE
安装依赖包报错

### ISSUE THREAD

**Issue by zhaodong0120** [arkcontrol/arkcontrol#1]
如题，详细错误如下：
ERRO[0044] exit status 2                                 source="services/service.go:232"

**Comment by ark-cloud** [comment]
由于服务器顶不住压力，导致IO TIMEOUT ，从而引起下载包异常，进而导致解压失败，我们正在升级服务器中。升级完成后，第一时间通知您。

**Comment by zhaodong0120** [comment]
ok，明白了

**Comment by ark-cloud** [comment]
目前已经通过CDN解决此类问题。
