### ISSUE TITLE
error: get private IP failed  获取不到我的ip，nginx 启动失败

### ISSUE THREAD

**Issue by shaxian** [arkcontrol/arkcontrol#11]
[root@localhost arkcontrol]# ./deploy-server 
INFO[0000] [sh -c \cp -rf ./nginx.conf ./nginx-1.8.0/nginx_conf/conf/] 
INFO[0000]                                               source="services/service.go:351"
ERRO[0000] error: get private IP failed.                
ERRO[0000] error: cannot get private ip                 
INFO[0000] start nginx                                   source="services/service.go:432"
ERRO[0003] error: get private IP failed.                
ERRO[0003] error: cannot get private ip                 
INFO[0003] Please access http://<nil>:90                 source="main/main.go:296"
ERRO[0003] error: get private IP failed.                
ERRO[0003] error: cannot get private ip                 
INFO[0003] Please access http://<nil>:90                 source="main/main.go:297"
ERRO[0003] error: get private IP failed.                
ERRO[0003] error: cannot get private ip                 
INFO[0003] Please access http://<nil>:90                 source="main/main.go:298"
ERRO[0149] error: get private IP failed.                
ERRO[0149] error: cannot get private ip

**Comment by shaxian** [comment]
nginx 我独立安装了，到浏览器安装下载依赖后 在数据库初始化又失败了 ，而且不支持多次执行deploy-server

**Comment by quan0012** [comment]
0.82的版本做了内网ip判断，如果不是10、172、192打头的ip会过滤掉。
考虑到某些情况下内网ip也有可能配置成公网的格式，所以下一个稳定版本中我们会去掉这个限制。

目前可以在http://mirror.cloud-ark.com/public_package/release/arkcontrol_v0.85.tar.gz下载最新的测试版尝试安装。

**Comment by shaxian** [comment]
> 0.82的版本做了内网IP判断，如果不是10172192打头的IP会过滤掉。
> 考虑到某些情况下内网IP也有可能配置成公网的格式，所以下一个稳定版本中我们会去掉这个限制。
> 
> 可以目前在[http://mirror.cloud-ark.com/public_package/release/arkcontrol_v0.85.tar.gz下载最新的测试版尝试安装。](http://mirror.cloud-ark.com/public_package/release/arkcontrol_v0.85.tar.gz%E4%B8%8B%E8%BD%BD%E6%9C%80%E6%96%B0%E7%9A%84%E6%B5%8B%E8%AF%95%E7%89%88%E5%B0%9D%E8%AF%95%E5%AE%89%E8%A3%85%E3%80%82)

**Comment by shaxian** [comment]
> > 0.82的版本做了内网IP判断，如果不是10172192打头的IP会过滤掉。
> > 考虑到某些情况下内网IP也有可能配置成公网的格式，所以下一个稳定版本中我们会去掉这个限制。
> > 目前可以在[http://mirror.cloud-ark.com/public_package/release/arkcontrol_v0.85.tar.gz下载最新的测试版尝试安装。](http://mirror.cloud-ark.com/public_package/release/arkcontrol_v0.85.tar.gz%E4%B8%8B%E8%BD%BD%E6%9C%80%E6%96%B0%E7%9A%84%E6%B5%8B%E8%AF%95%E7%89%88%E5%B0%9D%E8%AF%95%E5%AE%89%E8%A3%85%E3%80%82)

谢谢
