### ISSUE TITLE
README.md 论坛链接跳转错误

### ISSUE THREAD

**Issue by iwordz** [arkcontrol/arkcontrol#12]
点击forum.cloud-ark.com跳转错误。

**Comment by ark-cloud** [comment]
![image](https://user-images.githubusercontent.com/40416017/47481292-b54fc300-d865-11e8-8017-f9116a97961b.png)

我这边测试无问题，你那边报什么错误

**Comment by iwordz** [comment]
![1](https://user-images.githubusercontent.com/5894299/47990500-a0571780-e122-11e8-8719-1de663a43a48.png)
![2](https://user-images.githubusercontent.com/5894299/47990501-a0efae00-e122-11e8-80be-50e7beeb0c46.png)

**Comment by qiangchangjin** [comment]
已经修复
