### ISSUE TITLE
socat安装失败

### ISSUE THREAD

**Issue by pandakll** [arkcontrol/arkcontrol#13]
录入失败依赖安装出错socat安装失败，请问怎么排查

**Comment by xiebukaopu** [comment]
你好,麻烦查看下录入的机器agent_deploy/log/agent_deploy.log下的日志
如果没有错误信息的话,在agent_deploy/package/centos7/source/socat-1.7.3.2下手动执行
./configure
make && make install 
查看有没有报错信息
如果未定位到问题请添加微信15717194004, 我跟进一下

**Comment by pandakll** [comment]
解决了，感谢哈
这个是安装依赖的问题
Requires: glibc-common = 2.17-105.el7
           Installed: glibc-common-2.17-106.el7_2.4.x86_64
