### ISSUE TITLE
录入失败尝试启动arkagent失败

### ISSUE THREAD

**Issue by Peterliu2014** [arkcontrol/arkcontrol#14]
顺利安装各依赖，但是最终提示agent启动失败，日志里没找到具体失败原因

**Comment by zhaojian1987** [comment]
我也遇到了同样的问题。还请官方帮忙解答一下！！！

**Comment by running-tomato** [comment]
麻烦贴个图 @zhaojian1987 
对应agent目录下面的agent_deploy.log里面是否有报错日志？

**Comment by zhaojian1987** [comment]
居然有回复，有点小激动啊！！！感谢啊！


这是日志里的提示信息：





------------------ 原始邮件 ------------------
发件人: "forever18"<notifications@github.com>;
发送时间: 2019年9月24日(星期二) 下午4:29
收件人: "arkcontrol/arkcontrol"<arkcontrol@noreply.github.com>;
抄送: "智商"<707678692@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [arkcontrol/arkcontrol] 录入失败尝试启动arkagent失败 (#14)




麻烦贴个图 @zhaojian1987
 对应agent目录下面的agent_deploy.log里面是否有报错日志？

**Comment by running-tomato** [comment]
额，信息呢，没看到呀 @zhaojian1987

**Comment by zhaojian1987** [comment]
这个是agent端的日志信息：


time="2019-09-24T16:36:47+08:00" level=info msg="源码安装socat成功"
time="2019-09-24T16:36:47+08:00" level=info msg="尝试源码安装PV"
time="2019-09-24T16:36:51+08:00" level=info msg="源码安装PV成功"
time="2019-09-24T16:36:51+08:00" level=info msg="尝试源码安装PT工具"
time="2019-09-24T16:36:58+08:00" level=info msg="源码安装PT工具成功"
time="2019-09-24T16:36:58+08:00" level=info msg="依赖安装完成"
time="2019-09-24T16:36:58+08:00" level=info msg="尝试设置环境变量"
time="2019-09-24T16:36:58+08:00" level=info msg="尝试复制mysql tool"
time="2019-09-24T16:36:58+08:00" level=info msg="尝试启动arkagent;"
time="2019-09-24T16:36:59+08:00" level=info msg="录入失败尝试启动arkagent失败;"





------------------ 原始邮件 ------------------
发件人: "forever18"<notifications@github.com>;
发送时间: 2019年9月24日(星期二) 下午4:38
收件人: "arkcontrol/arkcontrol"<arkcontrol@noreply.github.com>;
抄送: "智商"<707678692@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [arkcontrol/arkcontrol] 录入失败尝试启动arkagent失败 (#14)




额，信息呢，没看到呀 @zhaojian1987

**Comment by running-tomato** [comment]
看样子像是启动agent的时候失败，可以看下agent.log日志，查看里面的报错。
要不您可以加下我微信：q329853099

**Comment by zhaojian1987** [comment]
给你回复了啊！再发一遍！







------------------ 原始邮件 ------------------
发件人: "forever18"<notifications@github.com>;
发送时间: 2019年9月24日(星期二) 下午4:38
收件人: "arkcontrol/arkcontrol"<arkcontrol@noreply.github.com>;
抄送: "智商"<707678692@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [arkcontrol/arkcontrol] 录入失败尝试启动arkagent失败 (#14)




额，信息呢，没看到呀 @zhaojian1987
