### ISSUE TITLE
 会开源吗？

### ISSUE THREAD

**Issue by eastdx** [arkcontrol/arkcontrol#15]
我内网安装，没外网，有all-in-one的安装包么？

**Comment by ark-cloud** [comment]
github上下载的最新的包，都不需要外网的

张冬洪   Donghong Zhang

C 北京极数云舟科技有限公司 

  M +86 18612720739    

  W zhangdh1113　

  Q 1037447289

  A 北京市海淀区上地东路35号颐泉汇公寓2号楼3层1-303 100085

**Comment by ark-cloud** [comment]
配置好yum源就行吧

张冬洪   Donghong Zhang

C 北京极数云舟科技有限公司 

  M +86 18612720739    

  W zhangdh1113　

  Q 1037447289

  A 北京市海淀区上地东路35号颐泉汇公寓2号楼3层1-303 100085
