### ISSUE TITLE
无限循环输出 - 开始安装Yum依赖...

### ISSUE THREAD

**Issue by YouDail** [arkcontrol/arkcontrol#16]
我手动安装了deploy.yaml里所有的包之后，编辑deploy.yaml, 编辑后的deploy.yaml文件内容如下:

package_url: http://mirror.cloud-ark.com:80/public_package/release
dependency:
  yums:
    - rsync
  pt_version: percona-toolkit-3.0.4

还是无限循环输出 - 开始安装Yum依赖... 。。。。。。。。。。。。。。。。。。。。。。。。。。。。。。

我不知道程序正在干什么，可以让用户自己选择是否执行yum 安装 依赖 这一步吗？？？

**Comment by quan0012** [comment]
安装目录下面的deploy.yaml，把yum里面的列表删掉，手动安装里面的依赖，然后再执行部署就可以了。
这周我们会发布新版本修复这个bug

**Comment by YouDail** [comment]
好的，我把yum里面的包都删除了，现在又无限循环报这样的：

- 开始安装Yum依赖...
- 开始安装pt工具...
安装percona-toolkit-3.0.4失败: error:exit status 127 stdout: stderr:sh: sudo: command not found

**Comment by YouDail** [comment]
好的，现在安装成功了

**Comment by YouDail** [comment]
上面的报错，安装 sudo 包解决了。
现在又开始报错： 

- 开始安装Arkcontrol所需配置库...
exit status 1 error:exit status 1 stdout: stderr:/opt/ark/arkdb/scripts/mysql_install_file: line 6: USER: unbound variable

请问这种报错又是什么原因呢

**Comment by quan0012** [comment]
是root用户安装的吗

**Comment by YouDail** [comment]
对，是root安装的

**Comment by quan0012** [comment]
检查一下这个文件的第6行，或者用root手动运行一下，看看有没有报错

**Comment by YouDail** [comment]
手动执行还是报错：
line 6: USER: unbound variable

这个文件是这样的逻辑：

     6	if [ $USER != 'root' ]; then
     7	    echo "Please run in as the root."
     8	    exit 1
     9	fi

我看了系统环境配置，$USER的值就是root，应该不会没获取啊

**Comment by YouDail** [comment]
嗯，好的，我加了个系统env ,指定了suer变量，现在可以往下走了，但是es这一块就报错了

- 开始初始化配置库
- 配置库初始化成功
- 配置监控...可能需要较长时间，请耐心等待
-- 开始配置elasticsearch...
es deploy:  exit status 255
exit status 255
安装已结束，自动退出...
time="2018-11-23T04:44:51Z" level=info msg="write config success!" source="services/service.go:178"
time="2018-11-23T04:44:51Z" level=info msg="es install path: /data/Arkcontrol/software, es-5.6.9" source="es/step.go:184"
time="2018-11-23T04:44:51Z" level=debug msg="wait es starting: Get http://192.168.0.149:9202/_cluster/health: dial tcp 192.168.0.149:9202: connect: connection refused" source="es/step.go:196"
time="2018-11-23T04:44:51Z" level=debug msg="wait es starting: unexpected end of JSON input" source="es/step.go:201"
time="2018-11-23T04:45:01Z" level=error msg="init system properties failed, error:exit status 255 stdout: stderr:sysctl: setting key \"vm.max_map_count\": Read-only file system\n" source="es/step.go:35"
time="2018-11-23T04:45:01Z" level=error msg="es deploy: exit status 255" source="monitor/deploy.go:24"
time="2018-11-23T04:45:01Z" level=error msg="exit status 255" source="services/service.go:121"
time="2018-11-23T04:45:01Z" level=info msg="Clean MySQL dir" source="services/service.go:432"
time="2018-11-23T04:45:04Z" level=warning msg="exit status 1 error:exit status 1 stdout: stderr:sudo: pam_open_session: Permission denied\nsudo: policy plugin failed session initialization\n" source="services/service.go:439"
time="2018-11-23T04:45:04Z" level=info msg="http: Server closed" source="ark-control-init/deploy_server.go:90"

**Comment by YouDail** [comment]
上面选择的是新建es，

重新安装，我选择已存在es，又报错 了

-- 开始配置elasticsearch...
es deploy:  检测到es进程已经存在，但是安装目录不存在，是否为僵尸进程？请清理，目录：/data/Arkcontrol/software/es-5.6.9
检测到es进程已经存在，但是安装目录不存在，是否为僵尸进程？请清理，目录：/data/Arkcontrol/software/es-5.6.9
安装已结束，自动退出...
