### ISSUE TITLE
docker安装ark，es配置失败

### ISSUE THREAD

**Issue by YouDail** [arkcontrol/arkcontrol#18]
我是以docker的方式运行ark，最新版本1.0.1，之前的问题都解决了，配置es这里，我选择新建es，就会报下面的错，这里我建议不要固执的执行 sysctl -w vm.max_map_count=262144 这个shell指令，应该做个判断，如果底层os没有设置vm.max_map_count=262144，再报错退出，下面是新建es的报错：

-- 开始配置elasticsearch...
es deploy:  exit status 255
exit status 255
安装已结束，自动退出...
time="2018-11-23T06:56:18Z" level=info msg="write config success!" source="services/service.go:178"
time="2018-11-23T06:56:18Z" level=info msg="es install path: /data/Arkcontrol/software, es-5.6.9" source="es/step.go:184"
time="2018-11-23T06:56:18Z" level=debug msg="wait es starting: Get http://172.17.0.2:9202/_cluster/health: dial tcp 172.17.0.2:9202: connect: connection refused" source="es/step.go:196"
time="2018-11-23T06:56:18Z" level=debug msg="wait es starting: unexpected end of JSON input" source="es/step.go:201"
time="2018-11-23T06:56:28Z" level=error msg="init system properties failed, error:exit status 255 stdout: stderr:sysctl: setting key \"vm.max_map_count\": Read-only file system\n" source="es/step.go:35"
time="2018-11-23T06:56:28Z" level=error msg="es deploy: exit status 255" source="monitor/deploy.go:24"
time="2018-11-23T06:56:28Z" level=error msg="exit status 255" source="services/service.go:121"
time="2018-11-23T06:56:28Z" level=info msg="Clean MySQL dir" source="services/service.go:432"
time="2018-11-23T06:56:31Z" level=warning msg="exit status 1 error:exit status 1 stdout: stderr:sudo: pam_open_session: Permission denied\nsudo: policy plugin failed session initialization\n" source="services/service.go:439"
time="2018-11-23T06:56:31Z" level=info msg="http: Server closed" source="ark-control-init/deploy_server.go:90"

使用现有es，这个也不能成功，报错如下：

-- 开始配置elasticsearch...
es deploy:  检测到es进程已经存在，但是安装目录不存在，是否为僵尸进程？请清理，目录：/data/Arkcontrol/software/es-5.6.9
检测到es进程已经存在，但是安装目录不存在，是否为僵尸进程？请清理，目录：/data/Arkcontrol/software/es-5.6.9
安装已结束，自动退出...
time="2018-11-23T06:08:31Z" level=info msg="Grant user: root, root to mysql" source="services/service.go:420"
time="2018-11-23T06:08:31Z" level=info msg="install mysql success" source="services/service.go:164"
time="2018-11-23T06:08:31Z" level=info msg="write config success!" source="services/service.go:178"
time="2018-11-23T06:08:31Z" level=info msg="es install path: /data/Arkcontrol/software, es-5.6.9" source="es/step.go:184"
time="2018-11-23T06:08:31Z" level=info msg="ES start success!" source="es/step.go:204"
time="2018-11-23T06:08:31Z" level=info msg="es install path: /data/Arkcontrol/software, es-5.6.9" source="es/step.go:218"
time="2018-11-23T06:08:31Z" level=error msg="es deploy: 检测到es进程已经存在，但是安装目录不存在，是否为僵尸进程？请清理，目录：/data/Arkcontrol/software/es-5.6.9" source="monitor/deploy.go:24"
time="2018-11-23T06:08:31Z" level=error msg="检测到es进程已经存在，但是安装目录不存在，是否为僵尸进程？请清理，目录：/data/Arkcontrol/software/es-5.6.9" source="services/service.go:121"
time="2018-11-23T06:08:31Z" level=info msg="Clean MySQL dir" source="services/service.go:432"
time="2018-11-23T06:08:35Z" level=info msg="http: Server closed" source="ark-control-init/deploy_server.go:90"

希望es这块的配置能改进下，新版本我在测试了，感谢各种开发者的辛劳付出

**Comment by YouDail** [comment]
好的，辛苦了

**Comment by YouDail** [comment]
今天我使用1.4.0版本安装，可以安装成功，进入登录页面，但根据 doc的 用户名: ark_control
密码： ark_control ，无法登录，后台也没有相关日志，查看数据库里Yearning库的core_account表，只有admin用户，请问怎样才能成功登录呢

**Comment by YouDail** [comment]
看到了这个表里的数据，但是试了很多次还是无法登录呢

**Comment by quan0012** [comment]
数据库里面有ark_control这个账号吗？
或者用浏览器的开发者工具调试一下，贴下login接口调用时候返回的response 和errcode，发下截图？

**Comment by quan0012** [comment]
13307是web的后端服务，可以在安装目录的bin目录下执行stop-acme.sh，然后执行start-acme.sh来启动，restart应该也可以，脚本会先停止web后端和ng，然后再启动，或者ps -ef | grep acme,查看一下acme-server是否启动

**Comment by YouDail** [comment]
感谢，执行restart就可以了👍👍👍👏👏👏
