### ISSUE TITLE
Error 6986: License is invalid or expire, this product is disabled, please check and update the license.

### ISSUE THREAD

**Issue by ZQXIN** [arkcontrol/arkcontrol#23]
Error 6986: License is invalid or expire, this product is disabled, please check and update the license.

**Comment by xiebukaopu** [comment]
你好,请确认是否在my.cnf指定了arkit_license_file
并且对应路径下确实存在arkit.key文件
如果存在,请检查arkit.key文件的md5值
```
shell> md5sum arkit.key
e6c7c7c768a1aa0d70567d5fdd87fd4c  arkit.key
```
