### ISSUE TITLE
请问什么时候能够支持RedHat和Oracle Linux呀？有计划么？

### ISSUE THREAD

**Issue by guogang1990** [arkcontrol/arkcontrol#26]
部署agent客户端时报不支持：
time="2019-03-15T14:45:07+08:00" level=info msg="host info {\"hostname\":\"xxxxxdb03\",\"uptime\":1313302,\"bootTime\":1551319005,\"procs\":389,\"os\":\"linux\",\"platform\":\"oracle\",\"platformFamily\":\"rhel\",\"platformVersion\":\"6.5\",\"kernelVersion\":\"3.8.13-16.2.1.el6uek.x86_64\",\"virtualizationSystem\":\"kvm\",\"virtualizationRole\":\"host\",\"hostid\":\"4c4c4544-0054-3810-8038-b3c04f355831\"}"

现在1.4.1的版本不支持Oracle Linux。

由于CentOS和RedHat以及Oracle Linux都是同源的，可以适当放开限制。

客户端安装的包差异不大。

希望大佬有计划支持一下，谢谢！

**Comment by qiangchangjin** [comment]
Hi
redhat 目前已经在适配中。
oracle linux 目前还在排期。

**Comment by guogang1990** [comment]
谢谢大佬！
