### ISSUE TITLE
still not init index template

### ISSUE THREAD

**Issue by huzilin** [arkcontrol/arkcontrol#3]
# 安装报错

具体报错如下：
```
INFO[0045] Grafana start success!                        source="grafana/deploy.go:168"
INFO[0045] grafana deploy success.                       source="monitor/deploy.go:33"
ERRO[0105] timeout: still not init index template        source="es/step.go:250"
ERRO[0105] init index template failed.                   source="monitor/deploy.go:38"
ERRO[0105] init index template failed.                   source="services/service.go:232"
```

请问如何解决呢

**Comment by quan0012** [comment]
有可能是因为内存使用率较高，es crash了，检查一下es是否存活？ 
命令：ps -ef | grep elasticsearch
或者查看一下log？贴一下具体的报错信息？

如果是因为es进程不存在，${installPath}/acme/download/es-5.6.9中查看log是否是因为内存不足导致进程退出，默认安装es时会占用机器一半的内存，可以将机器上不必要的进程停掉，减少内存占用，然后重新执行安装。

注：当前版本重新安装时需要重新执行./deploy-server命令。并且需要手动将上一次执行安装时默认启动的ng进程kill掉，否则./deploy-server会报错。（后续版本我们对此操作进行优化）
