### ISSUE TITLE
手动录入主机，创建路径失败

### ISSUE THREAD

**Issue by jackerzhou** [arkcontrol/arkcontrol#4]
创建路径/ark/data1失败

**Comment by quan0012** [comment]
有详细的报错日志吗？

**Comment by xiebukaopu** [comment]
您好,可以在用户沟通群里@孙凯,我加下您微信跟进下这个问题

**Comment by xiebukaopu** [comment]
@jackerzhou 您好!问题原因已经定位,您可以注释下 /etc/sudoers文件里的  Defaults requiretty
