### ISSUE TITLE
录入时，报percona-xtrabackup-24-2.4.9-1.el6.x86_64.rpm 安装失败

### ISSUE THREAD

**Issue by jianhaiqing** [arkcontrol/arkcontrol#9]
[root@sr-mysql-01 ~]# rpm -qa | grep percona
percona-release-0.1-6.noarch
percona-xtrabackup-2.3.10-1.el7.x86_64

本机上之前已经有安装过，这里安装用的是什么命令？

**Comment by quan0012** [comment]
可能是因为该机器之前已经用rpm安装过xtrabackup导致的冲突，尝试用rpm -e 删除之前的安装记录，再重新安装一下？

**Comment by jianhaiqing** [comment]
你们安装用的是什么命令？ yum install percona-xtrabackup-2.3.10-1.el7.x86_64.rpm ?
检查是否安装，安装的版本是否符合要求，这样会不会更好一点？

**Comment by quan0012** [comment]
应该是2.4。
恩，很好的建议，后面的版本我们跟进一下，尽量加一些提示
